// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/whatstrack-homepage/CommandCenter.tsx": () => import("../components/mockups/whatstrack-homepage/CommandCenter.tsx"),
  "./components/mockups/whatstrack-homepage/NeonNoir.tsx": () => import("../components/mockups/whatstrack-homepage/NeonNoir.tsx"),
  "./components/mockups/whatstrack-homepage/SleekSocial.tsx": () => import("../components/mockups/whatstrack-homepage/SleekSocial.tsx")
};
